### ISSUE TITLE
Unexpected hardhat test workflow

### ISSUE THREAD

**Issue by zZoMROT** [ItsNickBarry/hardhat-dependency-compiler#11]
When I try to test only one test file with `hardhat test test/something.sol` it passes 0 tests skipped all of them.
And when I try to test all test files with `hardhat test` some tests run without their `before(() => { ... })` block and variables inited in that blocks are with undefined values.
It will be useful to possible use hardhat args for the test command.

**Comment by ItsNickBarry** [comment]
I don't see any way that could be related to this plugin.  If you have evidence that it is, please reopen and comment here.
