### ISSUE TITLE
With the option keep:false solhint fails

### ISSUE THREAD

**Issue by krasi-georgiev** [ItsNickBarry/hardhat-dependency-compiler#3]
https://github.com/tellor-io/chorus/runs/2028100038

**Comment by ItsNickBarry** [comment]
@krasi-georgiev Try version `1.1.1` and let me know.

**Comment by ItsNickBarry** [comment]
@krasi-georgiev Reopen if `1.1.1` does not solve your problem.

**Comment by krasi-georgiev** [comment]
Thanks. will do
