### ISSUE TITLE
Error HH306: The 'file' parameter expects a value, but none was passed.

### ISSUE THREAD

**Issue by vittoridavide** [ItsNickBarry/hardhat-dependency-compiler#7]
I'm getting this error when passing a .sol file, 

` dependencyCompiler: {
    paths: [
      '@zircon/periphery/contracts/Token.sol',
      '@zircon/periphery/contracts/WETH.sol',
      // '@zircon/energy/contracts/*',
      '@zircon/energy/contracts/interfaces/IZirconEnergyRevenue.sol',
      '@zircon/energy/contracts/interfaces/IZirconEnergyFactory.sol',
      '@zircon/energy/contracts/ZirconEnergyFactory.sol',
    ],
  },`

the error is invoked only in the last contract

**Comment by ItsNickBarry** [comment]
Do you have this import commented out? `'@zircon/energy/contracts/*'`

Using `*` in your imports won't work, though that doesn't seem to be related to the error message.

Need more information.  What task are you running?
